db:
    build:
      context: .
    image: postgres:15-alpine  # or use 'build: ./postgres' if using custom Dockerfile
    environment:
      POSTGRES_DB: api-semanal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d api-semanal"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: