# Service for Java Backend
apiVersion: v1
kind: Service
metadata:
  name: java-backend-service
  namespace: production
spec:
  selector:
    app: java-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
# Service for Frontend
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: production
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
# Service for Postgres Database
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: production
spec:
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP