services:
  frontend:
    build: ./front-pedidos  # Path to React Dockerfile
    ports:
       - "80:80"      # Production (Nginx)
    environment:
      - CHOKIDAR_USEPOLLING=true  # Fix file watching in Docker
