name: Deploy para Produção

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Autenticar no Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_CREDENTIALS_JSON }}'

      - name: Obter credenciais do cluster GKE
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Aplicar configurações no Kubernetes (Produção)
        run: |
          kubectl apply -n production -f app-deployment.yaml
          kubectl apply -n production -f app-services.yaml
