name: Build, Test, and Deploy to AWS EC2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker (includes compose v2)
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build and test frontend
      - name: Build and Test Frontend
        working-directory: ./front-pedidos
        run: |
          # Build including test stage
          docker compose build
          # Run tests using the builder stage where npm exists
          docker compose run --rm builder npm test

      # Build and test backend
      - name: Build and Test Backend
        working-directory: ./back-pedidos
        run: |
          docker compose build
          docker compose run --rm backend mvn test

