name: Executar Testes

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Garantir permissão de execução para mvnw (backend)
        working-directory: back-pedidos
        run: chmod +x ./mvnw

      - name: Executar testes do backend
        working-directory: back-pedidos
        run: ./mvnw test

      - name: Instalar dependências do frontend
        working-directory: front-pedidos
        run: npm install

      - name: Verificar script de teste no frontend
        working-directory: front-pedidos
        run: |
          if grep -q '"test":' package.json; then
            npm test
          else
            echo "Nenhum script de teste encontrado no frontend."
          fi
